version: "2"
services:
  ravtel2-db-postgres:
    container_name: ravtel2-db-postgres
    image: postgres:13.3
    ports:
      - "5436:5432"
    volumes:
      - ./config/db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=ravteldb
      - POSTGRES_USER=ravteldb
      - POSTGRES_PASSWORD=ravteldb
