// Entity order
module.exports = {
  // Account
  GET_ACCOUNT_HANDLER_ACCOUNT_RECORD_NOT_FOUND: "GET_ACCOUNT_HANDLER_ACCOUNT_RECORD_NOT_FOUND",
  GET_ACCOUNT_HANDLER_OPERATION_FAILED: "GET_ACCOUNT_HANDLER_OPERATION_FAILED",
  GET_ACCOUNT_LIST_HANDLER_OPERATION_FAILED: "GET_ACCOUNT_LIST_HANDLER_OPERATION_FAILED",

  // Ledger
  GET_LEDGER_HANDLER_OPERATION_FAILED: "GET_LEDGER_HANDLER_OPERATION_FAILED",
  GET_LEDGER_HANDLER_LEDGER_RECORD_NOT_FOUND: "GET_LEDGER_HANDLER_LEDGER_RECORD_NOT_FOUND",
  GET_LEDGER_HANDLER_ID_INVALID: "GET_LEDGER_HANDLER_ID_INVALID",
  GET_LEDGER_LIST_HANDLER_OPERATION_FAILED: "GET_LEDGER_LIST_HANDLER_OPERATION_FAILED",
  POST_LEDGER_HANDLER_OPERATION_CONFLICTED: "POST_LEDGER_HANDLER_OPERATION_CONFLICTED",
  POST_LEDGER_HANDLER_OPERATION_FAILED: "POST_LEDGER_HANDLER_OPERATION_FAILED",

  // Product
  DELETE_PRODUCT_HANDLER_OPERATION_FAILED: "DELETE_PRODUCT_HANDLER_OPERATION_FAILED",
  DELETE_PRODUCT_HANDLER_PRODUCT_RECORD_NOT_FOUND: "DELETE_PRODUCT_HANDLER_PRODUCT_RECORD_NOT_FOUND",
  DELETE_PRODUCT_HANDLER_ID_INVALID: "DELETE_PRODUCT_HANDLER_ID_INVALID",
  GET_PRODUCT_HANDLER_OPERATION_FAILED: "GET_PRODUCT_HANDLER_OPERATION_FAILED",
  GET_PRODUCT_HANDLER_PRODUCT_RECORD_NOT_FOUND: "GET_PRODUCT_HANDLER_PRODUCT_RECORD_NOT_FOUND",
  GET_PRODUCT_HANDLER_ID_INVALID: "GET_PRODUCT_HANDLER_ID_INVALID",
  GET_PRODUCT_LIST_HANDLER_OPERATION_FAILED: "GET_PRODUCT_LIST_HANDLER_OPERATION_FAILED",
  POST_PRODUCT_HANDLER_OPERATION_CONFLICTED: "POST_PRODUCT_HANDLER_OPERATION_CONFLICTED",
  POST_PRODUCT_HANDLER_OPERATION_FAILED: "POST_PRODUCT_HANDLER_OPERATION_FAILED",
  POST_PRODUCT_HANDLER_NAME_CONFLICTED: "POST_PRODUCT_HANDLER_NAME_CONFLICTED",
  PUT_PRODUCT_HANDLER_PRODUCT_RECORD_NOT_FOUND: "PUT_PRODUCT_HANDLER_PRODUCT_RECORD_NOT_FOUND",
  PUT_PRODUCT_HANDLER_NAME_CONFLICTED: "PUT_PRODUCT_HANDLER_NAME_CONFLICTED",
  PUT_PRODUCT_HANDLER_ID_INVALID: "PUT_PRODUCT_HANDLER_ID_INVALID",
  PUT_PRODUCT_HANDLER_OPERATION_CONFLICTED: "PUT_PRODUCT_HANDLER_OPERATION_CONFLICTED",
  PUT_PRODUCT_HANDLER_OPERATION_FAILED: "PUT_PRODUCT_HANDLER_OPERATION_FAILED",

  // User
  DELETE_USER_HANDLER_OPERATION_FAILED: "DELETE_USER_HANDLER_OPERATION_FAILED",
  DELETE_USER_HANDLER_USER_RECORD_NOT_FOUND: "DELETE_USER_HANDLER_USER_RECORD_NOT_FOUND",
  DELETE_USER_HANDLER_UUID_INVALID: "DELETE_USER_HANDLER_UUID_INVALID",
  GET_USER_HANDLER_OPERATION_FAILED: "GET_USER_HANDLER_OPERATION_FAILED",
  GET_USER_HANDLER_USER_RECORD_NOT_FOUND: "GET_USER_HANDLER_USER_RECORD_NOT_FOUND",
  GET_USER_HANDLER_UUID_INVALID: "GET_USER_HANDLER_UUID_INVALID",
  GET_USER_LIST_HANDLER_OPERATION_FAILED: "GET_USER_LIST_HANDLER_OPERATION_FAILED",
  POST_USER_HANDLER_OPERATION_CONFLICTED: "POST_USER_HANDLER_OPERATION_CONFLICTED",
  POST_USER_HANDLER_OPERATION_FAILED: "POST_USER_HANDLER_OPERATION_FAILED",
  POST_USER_HANDLER_USERNAME_CONFLICTED: "POST_USER_HANDLER_USERNAME_CONFLICTED",
  PUT_USER_HANDLER_USER_RECORD_NOT_FOUND: "PUT_USER_HANDLER_USER_RECORD_NOT_FOUND",
  PUT_USER_HANDLER_USERNAME_CONFLICTED: "PUT_USER_HANDLER_USERNAME_CONFLICTED",
  PUT_USER_HANDLER_UUID_INVALID: "PUT_USER_HANDLER_UUID_INVALID",
  PUT_USER_HANDLER_OPERATION_CONFLICTED: "PUT_USER_HANDLER_OPERATION_CONFLICTED",
  PUT_USER_HANDLER_OPERATION_FAILED: "PUT_USER_HANDLER_OPERATION_FAILED",
};
