// Alphabetical order
module.exports = {
  EMPTY_AUTHORIZATION_HEADER: "EMPTY_AUTHORIZATION_HEADER",
  EMPTY_X_API_KEY: "EMPTY_X_API_KEY",
  INVALID_APP_OR_USER_AUTHORIZATION: "INVALID_APP_OR_USER_AUTHORIZATION",
  INVALID_AUTHORIZATION_TOKEN: "INVALID_AUTHORIZATION_TOKEN",
  INVALID_X_API_KEY: "INVALID_X_API_KEY",
  MALFORMED_AUTHORIZATION_TOKEN: "MALFORMED_AUTHORIZATION_TOKEN",
};
